# Generated by Django 5.1.7 on 2025-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tracking_number',
            field=models.CharField(max_length=10),
        ),
    ]
