# Generated by Django 5.1.7 on 2025-03-17 14:43

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_article_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tracking_number',
            field=models.CharField(default=app.models.generate_tracking_number, max_length=10),
        ),
    ]
