# Generated by Django 5.1.7 on 2025-03-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_article_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='konu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
