# Generated by Django 5.1.7 on 2025-03-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_editor_reviewer_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='email',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='alan',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
