# Generated by Django 5.1.7 on 2025-03-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_reviewer_email_reviewer_alan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='alan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
