# Generated by Django 5.1.7 on 2025-03-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_reviewer_alan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='alan',
        ),
    ]
