# Generated by Django 5.1.7 on 2025-03-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_reviewer_alan'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='alan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
