# Generated by Django 5.1.7 on 2025-03-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reviewer_alan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
                ('anon_pdf', models.FileField(upload_to='uploads/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.article')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reviewer')),
            ],
        ),
    ]
