# Generated by Django 5.1.7 on 2025-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_message_article_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='Anonimleştirilmemiş', max_length=50),
        ),
    ]
