# Generated by Django 5.1.7 on 2025-03-27 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anon_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='hakem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.reviewer'),
        ),
        migrations.AlterField(
            model_name='article',
            name='konu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(default='Yüklendi', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='tracking_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
