# Generated by Django 5.1.7 on 2025-03-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_article_anon_pdf_alter_article_hakem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(default='Anonimleştirilmemiş', max_length=255),
        ),
    ]
